# Exploration: Compact designs for integration density
# Focus on smaller, more integrated devices

design_space:
  a: [0.25, 0.35]      # Smaller spacings
  b: [0.08, 0.15]      
  r: [0.08, 0.14]      # Smaller holes
  R: [6.0, 12.0]       # Compact rings
  w: [0.35, 0.50]      # Narrower waveguides

simulation:
  resolution: 40       # Higher resolution for small features
  pml_width: 1.5       
  sim_time: 120        
  target_wavelength: 1.547

objective:
  num_disorder_runs: 7          
  disorder_std_dev_percent: 6.0  # Higher disorder for small features
  q_penalty_factor: 2.5          # Higher penalty for robustness

optimizer:
  n_initial_points: 8    
  n_iterations: 15       
  acquisition_function: "gp_hedge"